account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .import views
app_name='accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),#customer
    path('driver_login/', auth_views.LoginView.as_view(template_name='accounts/driver_login.html'), name='driver_login'),#driver
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp, name='signup'),#customer
    path('driver_signup/', views.DriverSignUp, name='DriverSignUp'),#driver
    path('profile/', views.profile, name='profile'),#customer
    path('driver_profile/', views.driver_profile, name='driver_profile'),#driver
    path('help/', views.help.as_view(), name='help'),
    path('customer_service/', views.customer_service.as_view(), name='customer_service'),

    path('driver_list/', views.driver_list, name='driver_list'),
    path('edit/<id>/', views.edit,name='edit'),
    path('DeliveryDetail/<int:id>/',views.DeliveryDetail.as_view(),name="DeliveryDetail" ),
    path('update/<id>/', views.update,name='update'),
    path('all_request_data/', views.all_request_data, name='all_request_data'),
]

driver/urls.py
from django.urls import path
# from .import views
# app_name="driver"
# urlpatterns = [
#       path('', views.driver, name='driver'),
#       path('edit/<id>/', views.edit,name='edit'),
#       path('update/<id>/', views.update,name='update'),
# ]

e_courier/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from account import views as user_views
from .import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/',user_views.profile, name='profile'),
    path('home',views.HomePage.as_view(),name='home'),
    path('account/',include('account.urls',namespace="account")),
    path('account/',include('django.contrib.auth.urls')),
    path('delivery_service/', include('delivery_service.urls')),
    path('notification/', include('notification.urls')),
    # path('', include('driver.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThankstPage.as_view(), name='thanks'),
]
if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.db.models.signals import post_save
STATUS_CHOICES = (
        ("Active", "Active"),
        ("Inactive", "Inactive"),
        ("Onrequest","Onrequest"),
    )
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self):
        super().save()

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

class driver_Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=100,choices=STATUS_CHOICES, default="Active")
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} driver Profile'

    def save(self):
        super().save()

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

account/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile,driver_Profile

         ## customer profile ##
class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

    #############       Driver profile           #####################
class DriverRegisterForm(UserCreationForm):
    email = forms.EmailField()
    car_details = forms.CharField(widget=forms.Textarea)
    phone = forms.CharField(max_length=12)
    class Meta:
        model = User
        fields = ['username', 'email','car_details','phone', 'password1', 'password2']

class DriverUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username', 'email']


class DriverProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = driver_Profile
        fields = ['image','status']

account/views.py
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from .import models
from .models import Profile,driver_Profile
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView,TemplateView
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView
# Create your views here.
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from .forms import DriverRegisterForm, DriverUpdateForm, DriverProfileUpdateForm
from delivery_service.models import delivery_product
from django.db.models import Count
################### customer login, signup views ######################################
def login(request):
    if request.method =="POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user=authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account not create")
        else:
            print("Someone tried to login and falied!")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request,'login.html',{})

def SignUp(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Your account has been created! You are now able to log in')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'accounts/signup.html', {'form': form})

@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'accounts/profile.html', context)

################### Driver login, signup views ######################################
def driver_login(request):
    if request.method =="POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user=authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('home'))
            else:
                return HttpResponse("Account not create")
        else:
            print("Someone tried to login and falied!")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request,'accounts/driver_login.html',{})

def DriverSignUp(request):
    if request.method == 'POST':
        form = DriverRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account has been created! You are now able to log in')
            return redirect('driver_login/')
    else:
        form = DriverRegisterForm()
    return render(request, 'accounts/driver_signup.html', {'form': form})

@login_required
def driver_profile(request):
    if request.method == 'POST':
        u_form = DriverUpdateForm(request.POST, instance=request.user)
        p_form = DriverProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.driver_profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Account has been updated!')
            return redirect('accounts/driver_profile')

    else:
        u_form = DriverUpdateForm(instance=request.user)
        p_form = DriverProfileUpdateForm(instance=request.user.driver_profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'accounts/driver_profile.html', context)

class help(TemplateView):
    template_name='accounts/help.html'

class customer_service(TemplateView):
    template_name='accounts/customer_service.html'

####################################################################################################

def all_request_data(request):
    #delivery_details = delivery_product.objects.get(pk=id)
    x = delivery_product.objects.all().count()
    list = delivery_product.objects.annotate(count=Count('id')).order_by('-Date')
    context = {
        'list':list,
        'x':x,
        #'delivery_details':delivery_details
    }
    return render(request,'accounts/all_request_data.html',context)
# def DeliveryDetail(request,id):
# 	delivery_detail=delivery_product.objects.get(pk=id)
# 	context={
# 	'delivery_detail': delivery_detail
# 	}
# 	return render(request,'accounts/delivery_detail.html',context)
class DeliveryDetail(DetailView):
    template_name='accounts/delivery_detail.html'
    def get_object(self):
        id_=self.kwargs.get("id")
        return get_object_or_404(delivery_product,id=id_)

############## Driver list #######
def driver_list(request):
    # x = driver_Profile.objects.all().count()
    # list = delivery_product.objects.annotate(count=Count('id')).order_by('-Date')
    driver_list = driver_Profile.objects.all()
    context = {
        'driver_list':driver_list
    }
    return render(request,'accounts/driver_list.html',context)

def edit(request,id):
	driver_list=driver_Profile.objects.get(pk=id)
	context={
	'driver_list': driver_list
	}
	return render(request,'accounts/edit.html',context)

def update(request, id):
    driver_list = driver_Profile.objects.get(pk=id)
    driver_list.status = request.GET['status']
    driver_list.save()
    return redirect(driver_list)

# def update(request, id):
#     driver_list = driver_profile.objects.get(pk=id)
#     driver_list.status = request.GET['status']
#     driver_list.name = request.GET['name']
#     driver_list.car_details = request.GET['car_details']
#     driver_list.phone = request.GET['phone']
#     driver_list.save()
#     return redirect("/")

account/templates/accounts/all_request_data.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
<style>
table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
}

tr:nth-child(even) {
    background-color: green;
}
h2{
  color: red;
}
</style>
</head>
<body>
<h2>{{x}} people send request for ordering. Please see:</h2>
username:{{user.username}}
<table>
  <tr>
    <th>From Location</th>
    <th>To Location</th>
    <th>Product Typet</th>
    <th>Date</th>
    <th>Edit</th>

  </tr>
{% for i in list %}
  <tr>
    <td>{{i.from_location}}</td>
    <td>{{i.to_location}}</td>
    <td>{{i.product_type}}</td>
    <td>{{i.Date}}</td>
    <td>ID-{{i.id}}<a class="btn btn-info" href="{% url 'accounts:DeliveryDetail' id=i.pk%}"">{{user.username}} Detail View</a>
    <!-- <td><a class="btn btn-info"href="{% url 'accounts:driver_list'%}">Search Driver</a> -->
      <a class="btn btn-info"href="#">Send</a></td>
  </tr>
  {% endfor %}
</table>
</body>
</html>
{% endblock %}

account/templates/accounts/customer_service.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}

  <div class="container">
    <h1>This is our Customer Service Page</h1>
      <a href="mailto:iamlaboniraz@gmail.com" class="btn btn-primary my-2">Cannect with me using Email</a>
  </div>
{% endblock %}

account/templates/accounts/delivery_detail.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  table {
      font-family: arial, sans-serif;
      border-collapse: collapse;
      width: 50%;
  }

  td, th {
      border: 1px solid #dddddd;
      text-align: left;
      padding: 8px;
  }

  tr:nth-child(even) {
      background-color: green;
  }
  h2{
    color: red;
  }
html {
  box-sizing: border-box;
}
*, *:before, *:after {
  box-sizing: inherit;
}

.column {
  float: left;
  width: 33.3%;
  margin-bottom: 16px;
  padding: 0 8px;
}

@media screen and (max-width: 650px) {
  .column {
    width: 100%;
    display: white;
  }
}

.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
}

.container {
  padding: 0 16px;
}

.container::after, .row::after {
  content: "";
  clear: both;
  display: table;
}

.title {
  color: grey;
}

.button {
  border: none;
  outline: 0;
  display: inline-block;
  padding: 8px;
  color: white;
  background-color: #4CAF50;
  text-align: center;
  cursor: pointer;
  width: 10%;
}

.button:hover {
  background-color: #555;
}
</style>
</head>
<body>

<br>

<div class="row">
    <form action="" method="post">
  <div class="column">
    <div class="card">
      <!-- <img src="/w3images/team1.jpg" alt="Jane" style="width:100%"> -->
      <div class="container">
        <h2>Name : {{user.username}}</h2>
        <p class="title">From Location: {{object.from_location}}</p>
        <p class="title">To Location: {{object.to_location}}</p>
        <p>Product Type is : {{object.product_type}}</p>

          <input type="hidden" name="object" value="{{ object.id }}">
          <input type="hidden" name="user" value="{{ user.id }}">
        <a href="#"><button type="submit" name="send" class="button">Send</button></a>
        <a href="#"><button type="submit" name="reject" class="button">Reject</button></a>

      </div>
    </div>
  </div>
        </form>
  </div>
</body>
</html>
{% endblock %}

account/templates/accounts/driver_list.html
{% extends 'base.html' %}
{% block content %}
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  table {
      font-family: arial, sans-serif;
      border-collapse: collapse;
      width: 80%;
  }

  td, th {
      border: 1px solid #dddddd;
      text-align: left;
      padding: 8px;
  }

  tr:nth-child(even) {
      background-color: green;
  }
  h2{
    color: red;
  }
</style>
</head>
<body>

<br>
<div class="container">
<h1>Driver List Here :</h1>

<table>
<tr>
  <th>user</th>
  <th>status</th>
  <th>Requset</th>
</tr>
{% for driver_list in driver_list %}
<tr>
  <td>{{ driver_list.user }}</td>
  <td>{{ driver_list.status }}</td>
  <td><a class="btn btn-info"href="{% url 'account:edit' id=driver_list.pk %}">Send</a></td>
</tr>
{% endfor %}
</table>
</div>
{% endblock%}

</body>
</html>

account/templates/accounts/driver_login.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Login" class="btn btn-default">
    </form>
</div>
{% endblock %}

account/templates/accounts/driver_profile.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load crispy_forms_tags %}
{% block content %}
<h1>Driver profile</h1>
<div class="container">
    <div class="row profile">
		<div class="col-md-3">
			<div class="profile-sidebar">
				<!-- SIDEBAR USERPIC -->
				<div class="profile-userpic">
				<img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
				</div>
				<!-- END SIDEBAR USERPIC -->
				<!-- SIDEBAR USER TITLE -->
				<div class="profile-usertitle">
					<div class="profile-usertitle-name">
						Hi {{ user.username }}
					</div>
				</div>
				<!-- END SIDEBAR USER TITLE -->
				<!-- SIDEBAR BUTTONS -->
				<div class="profile-userbuttons">
					<button type="button" class="btn btn-success btn-sm">{{ user.email }}</button>
				</div>
				<!-- END SIDEBAR BUTTONS -->
				<!-- SIDEBAR MENU -->
				<div class="profile-usermenu">
					<ul class="nav">
						<li class="active">
							<a href="#">
							<i class="glyphicon glyphicon-home"></i>
							Overview </a>
						</li>
						<li>
							<a href="#">
							<i class="glyphicon glyphicon-user"></i>
							Account Settings </a>
						</li>
						<li>
							<a href="{% url 'accounts:all_request_data'%}" target="_blank">
							<i class="glyphicon glyphicon-ok"></i>
							Tasks </a>
						</li>
						<li>
							<a href="#">
							<i class="glyphicon glyphicon-flag"></i>
							Help </a>
						</li>
					</ul>
				</div>
				<!-- END MENU -->
			</div>
		</div>
		<div class="col-md-9">
            <div class="profile-content">

         <div class="container">
         <h1>Update Profile</h1>

         <form method="post"enctype="multipart/form-data">
          {% csrf_token %}
              {% bootstrap_form u_form %}
              {% bootstrap_form p_form %}
            <input type="submit"class="btn btn-default" value="Update">
         </form>
         </div>
            </div>
		</div>
	</div>
  <h1>Delivery History</h1>
  <table class="table table-sm table-dark">
  <thead>

   <tr class="bg-primary">
      <th scope="col">From location</th>
      <th scope="col">To_location</th>
      <th scope="col">Product type</th>
      <th scope="col">Weight</th>
      <th scope="col">Date</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
      <td>12</td>
    </tr>

  </tbody>
</table>
</div>
<br>
<br>
{% endblock %}

account/templates/accounts/driver_signup.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
<div class="container">
  <h1>Sign Up</h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-default" value="Sign Up">
  </form>
</div>
{% endblock %}

account/templates/accounts/driver_task_page.html
<h1>hello</h1>

account/templates/accounts/edit.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<div class="small_div">
	<div class="container">
		<br>

	<h2>Edit for delivery request send:</h2>
	<hr>
	<form action ="/update/{{driver_list.id}}">
			<label class="form-group" for="status">status : </label>
		<select  class="form-control" type="text"name="status">
			<option value="{{driver_list.status}}" selected>{{driver_list.status}}</option>
			<option value="Inactive">Inactive</option>
	    <option value="Active">Active</option>
	    <option value="Onrequest">Onrequest</option>
  </select>
		<br>

			<label class="form-group" for="name">user : </label>
			<input class="form-control" type="text" name="user" value="{{driver_list.user}}" placeholder="{{driver_list.user}}">
		<br>

		<br>
		<input class="btn btn-success" type="submit" value="update">

	</form>
</div>
</div>
</body>
</html>
{% endblock %}

account/templates/accounts/help.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
<h1>This is our help page</h1>
</div>
{% endblock %}

account/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Login" class="btn btn-default">
    </form>
</div>
{% endblock %}

account/templates/accounts/profile.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load crispy_forms_tags %}
{% block content %}
<h1>Customer profile</h1>
<div class="container">
    <div class="row profile">
		<div class="col-md-3">
			<div class="profile-sidebar">
				<!-- SIDEBAR USERPIC -->
				<div class="profile-userpic">
				<img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
				</div>
				<!-- END SIDEBAR USERPIC -->
				<!-- SIDEBAR USER TITLE -->
				<div class="profile-usertitle">
					<div class="profile-usertitle-name">
						Hi {{ user.username }}
					</div>
				</div>
				<!-- END SIDEBAR USER TITLE -->
				<!-- SIDEBAR BUTTONS -->
				<div class="profile-userbuttons">
					<button type="button" class="btn btn-success btn-sm">{{ user.email }}</button>
				</div>
				<!-- END SIDEBAR BUTTONS -->
				<!-- SIDEBAR MENU -->
				<div class="profile-usermenu">
					<ul class="nav">
						<li class="active">
							<a href="#">
							<i class="glyphicon glyphicon-home"></i>
							Overview </a>
						</li>
						<li>
							<a href="#">
							<i class="glyphicon glyphicon-user"></i>
							Account Settings </a>
						</li>
						<li>
							<a href="#" target="_blank">
							<i class="glyphicon glyphicon-ok"></i>
							Tasks </a>
						</li>
						<li>
							<a href="#">
							<i class="glyphicon glyphicon-flag"></i>
							Help </a>
						</li>
					</ul>
				</div>
				<!-- END MENU -->
			</div>
		</div>
		<div class="col-md-9">
            <div class="profile-content">

         <div class="container">
         <h1>Update Profile</h1>

         <form method="post"enctype="multipart/form-data">
          {% csrf_token %}
              {% bootstrap_form u_form %}
              {% bootstrap_form p_form %}
            <input type="submit"class="btn btn-default" value="Update">
         </form>
         </div>
            </div>
		</div>
	</div>
  <h1>Delivery History</h1>
  <table class="table table-sm table-dark">
  <thead>

   <tr class="bg-primary">
      <th scope="col">From location</th>
      <th scope="col">To_location</th>
      <th scope="col">Product type</th>
      <th scope="col">Weight</th>
      <th scope="col">Date</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
      <td>12</td>
    </tr>

  </tbody>
</table>
</div>
<br>
<br>
{% endblock %}

account/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
<div class="container">
  <h1>Sign Up</h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-default" value="Sign Up">
  </form>
</div>
{% endblock %}