account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .import views
app_name='accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),#customer
    path('driver_login/', auth_views.LoginView.as_view(template_name='accounts/driver_login.html'), name='driver_login'),#driver
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp, name='signup'),#customer
    path('driver_signup/', views.DriverSignUp, name='DriverSignUp'),#driver
    path('profile/', views.profile, name='profile'),#customer
    path('driver_profile/', views.driver_profile, name='driver_profile'),#driver
    path('help/', views.help.as_view(), name='help'),
    path('customer_service/', views.customer_service.as_view(), name='customer_service'),

    path('driver_list/', views.driver_list, name='driver_list'),
    path('edit/<id>/', views.edit,name='edit'),
    path('DeliveryDetail/<int:id>/',views.DeliveryDetail.as_view(),name="DeliveryDetail" ),
    path('update/<id>/', views.update,name='update'),
    path('all_request_data/', views.all_request_data, name='all_request_data'),
]

delivery_service/urls.py
from django.urls import path
from .import views
from .views import(
   delivery_request,
   wait_sms,
   sms_send
)
app_name='delivery_service'
urlpatterns = [
      path('', views.delivery_request, name='delivery_request'),
      path('sms_send/', views.sms_send, name='sms_send'),
      path('wait_sms',views.wait_sms,name='wait_sms')
]

driver/urls.py
from django.urls import path
# from .import views
# app_name="driver"
# urlpatterns = [
#       path('', views.driver, name='driver'),
#       path('edit/<id>/', views.edit,name='edit'),
#       path('update/<id>/', views.update,name='update'),
# ]

e_courier/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from account import views as user_views
from .import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/',user_views.profile, name='profile'),
    path('home',views.HomePage.as_view(),name='home'),
    path('account/',include('account.urls',namespace="account")),
    path('account/',include('django.contrib.auth.urls')),
    path('delivery_service/', include('delivery_service.urls')),
    path('notification/', include('notification.urls')),
    # path('', include('driver.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThankstPage.as_view(), name='thanks'),
]
if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<title>blog</title>
	<!-- Bootstrap -->
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Medium style Editor -->
 <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
	<!-- Custom css -->
	<link rel="stylesheet" href="{% static 'simplesocial/css/master.css' %}">
	<!-- Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Ranga&display=swap" rel="stylesheet">
</head>

<body>


  <!-- Navbar -->
<nav class="navbar mynav" role="navigation"id="navbar">
 <div class="container">
   <a class="navbar-brand mynav" href="{% url 'home' %}">Star Social</a>

   <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
     <li><a href="{% url 'delivery_service:delivery_request' %}" class="btn btn-simple">Delivery Service</a></li>
     <li><a href="{% url 'accounts:customer_service' %}"class="btn btn-simple">Customer Service</a></li>
		 <li><a href="{% url 'profile' %}"class="btn btn-simple">Profile</a></li>
		  <li><a href="{% url 'accounts:driver_profile' %}"class="btn btn-simple">Driver Profile</a></li>
     <li><a href="{% url 'accounts:logout' %}"class="btn btn-simple">Log Out</a></li>
     <li>
       <a class="btn btn-simple">welcome:{{user.username}}</a>
     </li>
     {% else %}
     <li><a href="{% url 'accounts:customer_service' %}"class="btn btn-simple">Customer Service</a></li>
     <li><a href="{% url 'accounts:help' %}"class="btn btn-simple">Help</a></li>
     <li><a href="{% url 'accounts:login' %}"class="btn btn-simple"><span class="glyphicon glyphicon-user"></span></a></li>
		 <li><a href="{% url 'accounts:driver_login' %}"class="btn btn-simple"><span class="glyphicon glyphicon-user"></span></a></li>
     <li><a href="{% url 'accounts:signup' %}"class="btn btn-simple">Sign Up</a></li>
		 <li><a href="{% url 'accounts:DriverSignUp' %}"class="btn btn-simple">Driver Sign Up</a></li>
     {% endif %}
   </ul>
 </div>

</nav>

<div class="container">
  {% block content %}

  {% endblock %}

</div>
<canvas id="canvas"></canvas>

</body>
  <script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" ></script>
</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>E-courier service</title>

  <!-- Bootstrap Core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom Fonts -->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
  <link href="{% static 'vendor/simple-line-icons/css/simple-line-icons.css' %}" rel="stylesheet">

  <!-- Custom CSS -->
  <link href="{% static 'css/stylish-portfolio.min.css' %}" rel="stylesheet">

</head>

<body id="page-top">
  <!-- Navigation -->
  <a class="menu-toggle rounded" href="#">
    <i class="fas fa-bars"></i>
  </a>
  <nav id="sidebar-wrapper">
    <ul class="sidebar-nav">
      <li class="sidebar-brand">
    {% if user.is_authenticated %}
      <a href="{% url 'delivery_service:delivery_request' %}" class="btn btn-simple">Delivery Service</a>
    </li>
    <li  class="sidebar-brand">
      <a href="{% url 'accounts:customer_service' %}"class="btn btn-simple">Customer Service</a>
    </li>
    <li  class="sidebar-brand">
      <a href="{% url 'profile' %}"class="btn btn-simple">Profile</a>
    </li>
    <li  class="sidebar-brand">
      <a href="{% url 'accounts:logout' %}"class="btn btn-simple">Log Out</a>
    </li>
    <li  class="sidebar-brand">
      <a class="btn btn-simple">welcome:{{user.username}}</a>
    </li>
    {% else %}
    <a class="js-scroll-trigger" href="#page-top">E-courier service</a>
    </li>
    <li class="sidebar-nav-item">
    <a class="js-scroll-trigger" href="{% url 'accounts:login' %}">LogIn</a>
    </li>
    <li class="sidebar-nav-item">
    <a class="js-scroll-trigger" href="{% url 'accounts:signup' %}">SignUp</a>
    </li>
    <li class="sidebar-nav-item">
    <a class="js-scroll-trigger" href="#page-top">Home</a>
    </li>
    <li class="sidebar-nav-item">
    <a class="js-scroll-trigger" href="#about">About</a>
    </li>
    <!-- <li class="sidebar-nav-item">
    <a class="js-scroll-trigger" href="#services">Services</a>
    </li> -->
    <li class="sidebar-nav-item">
    <a class="js-scroll-trigger" href="#portfolio">Portfolio</a>
    </li>
    <li class="sidebar-nav-item">
    <a class="js-scroll-trigger" href="#contact">Contact</a>
    {% endif %}
      </li>
    </ul>
  </nav>
  <!-- Header -->
  <header class="masthead d-flex">
    <div class="container text-center my-auto">
      <h1 class="mb-1">E-courier service</h1>
      <h3 class="mb-5">
        <em>Welcome to our website!</em>
      </h3>
      <a class="btn btn-primary btn-xl js-scroll-trigger" href="#about">Information</a>
    </div>
    <div class="overlay"></div>
  </header>

  <!-- About -->
  <section class="content-section bg-light" id="about">
    <div class="container text-center">
      <div class="row">
        <div class="col-lg-10 mx-auto">
          <h2>This is about page</h2>
          <p class="lead mb-5">We are doing a e-courier project for RMG industry<br>
            <a href="https://en.wikipedia.org/wiki/Textile_industry_in_Bangladesh">RMG</a>!</p>
          <a class="btn btn-dark btn-xl js-scroll-trigger" href="#contact">Contact with us</a>
        </div>
      </div>
    </div>
  </section>

<!-- Registration -->
<section class="content-section bg-primary text-white text-center" id="signup">
  <div class="container">
    <div class="content-section-heading">
      <h3 class="text-secondary mb-0">Registration</h3>
      <h2 class="mb-5">Click Here For Registration</h2>
    </div>
    <div class="row">
      <div class="col-lg-4 col-md-6 mb-5 mb-lg-0">
        <a href="{% url 'accounts:signup' %}"class="btn btn-simple">
        <span class="service-icon rounded-circle mx-auto mb-3">
          <i class="icon-screen-smartphone"></i>
        </span>
        </a>
        <h4>
          <strong>Sign Up</strong>
        </h4>
        <p class="text-faded mb-0">Click Here For Sign Up</p>
      </div>
      <div class="col-lg-4 col-md-6 mb-5 mb-lg-0">
        <a href="{% url 'accounts:login' %}"class="btn btn-simple">
        <span class="service-icon rounded-circle mx-auto mb-3">
          <i class="icon-pencil"></i>
        </span></a>
        <h4>
          <strong>Log In</strong>
        </h4>
        <p class="text-faded mb-0">Click Here For Login</p>
      </div>
      <div class="col-lg-4 col-md-6 mb-5 mb-md-0">
        <a href="https://www.facebook.com/"class="btn btn-simple">
        <span class="service-icon rounded-circle mx-auto mb-3">
          <i class="icon-like"></i>
        </span>
        </a>
        <h4>
          <strong>Like Page</strong>
        </h4>
        <p class="text-faded mb-0">Like Our
          Facebook Page<i class="fas fa-heart"></i>
          </p>
      </div>
    </div>
  </div>
</section>


  <!-- Callout -->


  <!-- Portfolio -->
  <section class="content-section" id="portfolio">
    <div class="container">
      <div class="content-section-heading text-center">
        <h3 class="text-secondary mb-0">Portfolio</h3>
        <h2 class="mb-5">Service picture</h2>
      </div>
      <div class="row no-gutters">
        <div class="col-lg-6">
          <a class="portfolio-item" href="#">
            <span class="caption">
              <span class="caption-content">
                <h2>Stationary</h2>
                <p class="mb-0">A yellow pencil with envelopes on a clean, blue backdrop!</p>
              </span>
            </span>
            <img class="img-fluid" src="{% static 'img/portfolio-1.jpg' %}" alt="">
          </a>
        </div>
        <div class="col-lg-6">
          <a class="portfolio-item" href="#">
            <span class="caption">
              <span class="caption-content">
                <h2>Ice Cream</h2>
                <p class="mb-0">A dark blue background with a colored pencil, a clip, and a tiny ice cream cone!</p>
              </span>
            </span>
            <img class="img-fluid" src="{% static 'img/portfolio-2.jpg' %}" alt="">
          </a>
        </div>
        <div class="col-lg-6">
          <a class="portfolio-item" href="#">
            <span class="caption">
              <span class="caption-content">
                <h2>Strawberries</h2>
                <p class="mb-0">Strawberries are such a tasty snack, especially with a little sugar on top!</p>
              </span>
            </span>
            <img class="img-fluid" src="{% static 'img/portfolio-3.jpg' %}" alt="">
          </a>
        </div>
        <div class="col-lg-6">
          <a class="portfolio-item" href="#">
            <span class="caption">
              <span class="caption-content">
                <h2>Workspace</h2>
                <p class="mb-0">A yellow workspace with some scissors, pencils, and other objects.</p>
              </span>
            </span>
            <img class="img-fluid" src="{% static 'img/portfolio-4.jpg' %}" alt="">
          </a>
        </div>
      </div>
    </div>
  </section>

  <!-- Call to Action -->


  <!-- Map -->
  <section id="contact" class="map">
    <iframe width="100%" height="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Twitter,+Inc.,+Market+Street,+San+Francisco,+CA&amp;aq=0&amp;oq=twitter&amp;sll=28.659344,-81.187888&amp;sspn=0.128789,0.264187&amp;ie=UTF8&amp;hq=Twitter,+Inc.,+Market+Street,+San+Francisco,+CA&amp;t=m&amp;z=15&amp;iwloc=A&amp;output=embed"></iframe>
    <br />
    <small>
      <a href="https://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=Twitter,+Inc.,+Market+Street,+San+Francisco,+CA&amp;aq=0&amp;oq=twitter&amp;sll=28.659344,-81.187888&amp;sspn=0.128789,0.264187&amp;ie=UTF8&amp;hq=Twitter,+Inc.,+Market+Street,+San+Francisco,+CA&amp;t=m&amp;z=15&amp;iwloc=A"></a>
    </small>
  </section>

  <!-- Footer -->
  <footer class="footer text-center">
    <div class="container">
      <ul class="list-inline mb-5">
        <li class="list-inline-item">
          <a class="social-link rounded-circle text-white mr-3" href="#">
            <i class="icon-social-facebook"></i>
          </a>
        </li>
        <li class="list-inline-item">
          <a class="social-link rounded-circle text-white mr-3" href="#">
            <i class="icon-social-twitter"></i>
          </a>
        </li>
        <li class="list-inline-item">
          <a class="social-link rounded-circle text-white" href="#">
            <i class="icon-social-github"></i>
          </a>
        </li>
      </ul>

    </div>
  </footer>

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded js-scroll-trigger" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Plugin JavaScript -->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'js/stylish-portfolio.min.js' %}"></script>

</body>

</html>

templates/test.html
{% extends 'base.html' %}
{% block content %}
<h1>You are now logged in!</h1>
{% endblock %}

templates/thanks.html
{% extends 'base.html' %}
{% block content %}
<h1>Thanks for visiting, come back soon!</h1>
{% endblock %}